default: &defaults
  blog:
    title: "RoR Blog"
  admin:
    user: "admin"
    password: "password" #恐ろしの直書き
  paginate:
    per_page: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
